version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: narada-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  narada-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: narada-ai-app
    ports:
      - "3000:3000"
    environment:
      # Qdrant Configuration
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION_NAME=narada_vectors
      - QDRANT_API_KEY=${QDRANT_API_KEY:-}
      
      # AI/LLM API Keys (set these in .env file)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - COHERE_API_KEY=${COHERE_API_KEY:-}
      - OLLAMA_API_URL=${OLLAMA_API_URL:-}
      - OLLAMA_FAST_MODEL=${OLLAMA_FAST_MODEL:-}
      - OLLAMA_QUALITY_MODEL=${OLLAMA_QUALITY_MODEL:-}
      
      # Search API Keys
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY:-}
      - TAVILY_API_KEY=${TAVILY_API_KEY:-}
      - SERP_API_KEY=${SERP_API_KEY:-}
      
      # Redis/Upstash (for rate limiting)
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL:-}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN:-}
      
      # LLM Configuration
      - LLM_PROVIDER=${LLM_PROVIDER:-openai}
      - EMBEDDING_PROVIDER=${EMBEDDING_PROVIDER:-openai}
      - SEARCH_PROVIDER=${SEARCH_PROVIDER:-tavily}
      - VECTOR_DB_PROVIDER=${VECTOR_DB_PROVIDER:-qdrant}
      
      # Next.js Configuration
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      qdrant:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/check-env"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  qdrant_storage:
    driver: local

networks:
  default:
    name: narada-network
