use_default_settings: true

server:
  secret_key: "narada-searxng-local-secret-key-change-in-production"
  limiter: false
  image_proxy: true

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json

redis:
  url: false
